label: Tooltip
status: ready

variants:
  - name: default
    label: Default
    context:
      tooltip:
        direction: "top"
        text: Tooltip on top
        button_text: Show on top
  - name: utilities
    label: With utilities
    context:
      tooltip:
        classes: margin-left-3 margin-top-2 border padding-left-6 padding-right-2 padding-top-5 padding-bottom-1 bg-base-lightest
